# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QQZero' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'SnapKit', '~> 3.0.2'             # 约束布局
	pod 'MBProgressHUD', '~> 0.9.2'       # 蒙版提示

end
